version: 1
sequences:
- protein:
    id: H
    sequence: EVQLLESGGGLVQPGGSLRLSCAASGLTFRSYAMTWVRQAPGKGLEWVSGISVSGGITYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKRGAAVGSFDYWGQGTLVTVSS
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8CYH_0.csv
- protein:
    id: L
    sequence: DIQMTQSPSSLSASVGDRVTITCRSSQGIGSWLAWYQQKPEKAPQSLIYAASSLQSGVPSRFSGSGSGTDFTLTISNLQPEDFATYYCQQYNSYPLTFGGGTKVEIK
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8CYH_1.csv
- protein:
    id: A
    sequence: EVEKTACPSGKKAREIDESLIFYKKWELEACVDAALLATQMDRVNAIPFTYEQLDVLKHKLDELYPQGYPESVIQHLGYLFLKMSPEDIRKWNVTSLETLKALLEVNKGHEMSPQAPRRPLPQVATLIDRFVKGRGQLDKDTLDTLTAFYPGYLCSLSPEELSSVPPSSIWAVRPQDLDTCDPRQLDVLYPKARLAFQNMNGSEYFVKIQSFLGGAPTEDLKALSQQNVSMDLATFMKLRTDAVLPLTVAEVQKLLGPHVEGLKAEERHRPVRDWILRQRQDDLDTLGLGLQGGIPNGYLVLDLSMQEALGSGLNDIFEAQKIEWHE
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8CYH_2.csv
